### ISSUE TITLE
Add hint on building/installation into README.md

### ISSUE THREAD

**Issue by ghost** [wagenadl/eln#1]
I had to run `sudo zypper install libqt4-devel` on OpenSUSE to get the `qmake` command together with all kinds of UI devel libraries.

**Comment by wagenadl** [comment]
Thank you for your note. Since it might be useful to others, I'd like to somehow post it with the project. Do you know how to do that?

**Comment by ghost** [comment]
Hi, most projects keep a simple "how to build/run" section in the `README.md` pushed to master branch. It's then immediately visible for all visitors of your Github landing page.
However, due to #2, my suggestion above may not be sufficient.
You could start with describing what you did to make the code run, and on what system.
