### ISSUE TITLE
Hover hint text appears as white text on light yellow background.

### ISSUE THREAD

**Issue by thadeausmaximus** [wagenadl/eln#15]
Using notedeln 1.4.0 on Linux mint 21.3

When hovering over the buttons the popup hint text appears as white text in a light yellow box and is mostly unreadable. 
Small thing but makes learning to use the program difficult. 

It was taking the default text color from the theme. When in dark mode text appears white. When I switched to a light light mode theme text became black and readable.

**Comment by wagenadl** [comment]
Fixed by release v1.5.4
