### ISSUE TITLE
allow port numbers for remote git archives

### ISSUE THREAD

**Issue by oe1rsa** [wagenadl/eln#3]
Thank you for this great piece of Software!

Just one wish: Could you please allow to specify a different port than 22 for the ssh access when creating or cloning a remote notebook? I.e. I'd need to specify "host.dom:port". Currently the hostname lookup fails when trying to do so.

Best, Roland

**Comment by wagenadl** [comment]
That's an excellent idea. I'll try to implement it later this month.

- Daniel

**Comment by wagenadl** [comment]
Solved in v. 1.2.12. You can now say "host.domain:port" in the "Host" field and it should work as expected. Please reopen if it still doesn't work for you.
