### ISSUE TITLE
Pressing escape in footnote edit should return cursor to original position in main text

### ISSUE THREAD

**Issue by jonnew** [wagenadl/eln#4]
Pressing <kbd>Ctrl</kbd> + <kbd>N</kbd> while editing text will create footnote. Pressing <kbd>Esc</kbd> while editing the footnote halts footnote editing, but leaves the cursor in an apparently undefined state. I suggest that the cursor should be returned to the position in the main text at which the footnote was originally requested.

version: cca5af9e9833

**Comment by wagenadl** [comment]
Excellent idea. Sadly, surprisingly difficult to implement given current data structures. I'll get to it eventually.

**Comment by wagenadl** [comment]
Done in a3d3a9c. This works if the cursor got moved into the footnote by Ctrl-N. It does not (yet) work if the user clicked on an existing footnote.
