### ISSUE TITLE
Functionally of remote archiving ambiguous

### ISSUE THREAD

**Issue by jonnew** [wagenadl/eln#6]
I read a followed the section `3.20 Archiving (version control)` in the manual. I followed the black diamond instructions for creating a remotely archived notebook on our lab's NAS. Everything seemed to work (e.g. the `testing.nb.git` notebook appeared on the server where I wanted it to). When I open the notebook locally a dialog pops up saying "updating from git". However, when I look at the status of the git repo on the remote server by logging in, it never seems to update. When I attempt to create another notebook using the remote copy, it fails because there do not seem to be any commits. Do I have to trigger commits manually? If so, how?

**Comment by wagenadl** [comment]
You should not have to commit manually. It happens automatically every few minutes, or whenever you close eln. Can you send me the contents of your "style.json" file in the notebook as well as the ".git/config" file? Please send me these for your original notebook as well as for the supposed clone.
One question I have is, how did you "create another notebook using the remote copy"? Did you do "clone hosted notebook for local use"?

**Comment by wagenadl** [comment]
Closing this issue after long nonactivity. Creating a remotely hosted notebook works when I follow the instructions.
