### ISSUE TITLE
Adding videos to notebooks

### ISSUE THREAD

**Issue by kephale** [wagenadl/eln#7]
Howdy

I'm not sure how hard this is in QT, but would it be possible to embed videos in notebooks?

We're looking at eln for microscopy and being able to show rendered videos would be super useful.

Thank you!

**Comment by wagenadl** [comment]
Are you still interested? This would seem to be possible with a QGraphicsVideoItem. I would be interested in corresponding about what the UI should look like for it to be maximally useful to you.

**Comment by wagenadl** [comment]
Implemented in v. 1.5.0. Check it out!
